"""add housekeeping

Revision ID: 0c818566a228
Revises: 87b9a0e244d2
Create Date: 2026-09-05 22:28:40.433004
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0c818566a228'
down_revision: str | None = '87b9a0e244d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hk_room_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('clean', 'dirty', 'inspected', 'out_of_service', name='roomhousekeepingstatus', native_enum=False, length=40), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['inv_rooms.id'], name=op.f('fk_hk_room_state_room_id_inv_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hk_room_state'))
    )
    op.create_index(op.f('ix_hk_room_state_room_id'), 'hk_room_state', ['room_id'], unique=True)
    op.create_table('hk_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='housekeepingtaskstatus', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['auth_users.id'], name=op.f('fk_hk_tasks_assigned_to_auth_users')),
    sa.ForeignKeyConstraint(['room_id'], ['inv_rooms.id'], name=op.f('fk_hk_tasks_room_id_inv_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hk_tasks'))
    )
    op.create_index(op.f('ix_hk_tasks_assigned_to'), 'hk_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_hk_tasks_room_id'), 'hk_tasks', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hk_tasks_room_id'), table_name='hk_tasks')
    op.drop_index(op.f('ix_hk_tasks_assigned_to'), table_name='hk_tasks')
    op.drop_table('hk_tasks')
    op.drop_index(op.f('ix_hk_room_state_room_id'), table_name='hk_room_state')
    op.drop_table('hk_room_state')
    # ### end Alembic commands ###
