"""room adjoining_room_id

Revision ID: 33755596570f
Revises: 67a9866213c8
Create Date: 2026-08-30 18:36:47.161845
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '33755596570f'
down_revision: str | None = '67a9866213c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv_rooms', sa.Column('adjoining_room_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inv_rooms_adjoining_room_id'), 'inv_rooms', ['adjoining_room_id'], unique=False)
    op.create_foreign_key(op.f('fk_inv_rooms_adjoining_room_id_inv_rooms'), 'inv_rooms', 'inv_rooms', ['adjoining_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inv_rooms_adjoining_room_id_inv_rooms'), 'inv_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_inv_rooms_adjoining_room_id'), table_name='inv_rooms')
    op.drop_column('inv_rooms', 'adjoining_room_id')
    # ### end Alembic commands ###
