"""add room views

Revision ID: 5498c2f83b05
Revises: 0c818566a228
Create Date: 2026-09-06 20:56:03.414599
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5498c2f83b05'
down_revision: str | None = '0c818566a228'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_room_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('surcharge_minor', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_room_views'))
    )
    op.create_index(op.f('ix_inv_room_views_code'), 'inv_room_views', ['code'], unique=True)
    op.add_column('inv_rooms', sa.Column('view_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inv_rooms_view_id'), 'inv_rooms', ['view_id'], unique=False)
    op.create_foreign_key(op.f('fk_inv_rooms_view_id_inv_room_views'), 'inv_rooms', 'inv_room_views', ['view_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inv_rooms_view_id_inv_room_views'), 'inv_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_inv_rooms_view_id'), table_name='inv_rooms')
    op.drop_column('inv_rooms', 'view_id')
    op.drop_index(op.f('ix_inv_room_views_code'), table_name='inv_room_views')
    op.drop_table('inv_room_views')
    # ### end Alembic commands ###
