"""initial schema

Revision ID: 67a9866213c8
Revises: 
Create Date: 2026-08-29 22:54:50.553115
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '67a9866213c8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('auth_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_permissions'))
    )
    op.create_index(op.f('ix_auth_permissions_code'), 'auth_permissions', ['code'], unique=True)
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_roles'))
    )
    op.create_index(op.f('ix_auth_roles_code'), 'auth_roles', ['code'], unique=True)
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_users')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_users_email'))
    )
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('bill_tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fixed_minor', sa.Integer(), nullable=True),
    sa.Column('applies_to_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_tax_rules'))
    )
    op.create_table('guest_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_travel_agent', sa.Boolean(), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_companies'))
    )
    op.create_index(op.f('ix_guest_companies_name'), 'guest_companies', ['name'], unique=False)
    op.create_table('inv_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('postcode', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_property'))
    )
    op.create_table('inv_room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_adults', sa.Integer(), nullable=False),
    sa.Column('standard_occupancy', sa.Integer(), nullable=False),
    sa.Column('bed_configuration', sa.String(length=120), nullable=False),
    sa.Column('size_sqm', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('overbooking_allowance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_room_types'))
    )
    op.create_index(op.f('ix_inv_room_types_code'), 'inv_room_types', ['code'], unique=True)
    op.create_table('rate_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('meal_plan', sa.Enum('room_only', 'breakfast', 'half_board', 'full_board', name='mealplan', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_rate_plan_id', sa.Integer(), nullable=True),
    sa.Column('derived_mode', sa.Enum('percent', 'amount', name='derivedmode', native_enum=False, length=40), nullable=True),
    sa.Column('derived_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('free_cancel_until_days', sa.Integer(), nullable=False),
    sa.Column('cancellation_penalty_nights', sa.Integer(), nullable=False),
    sa.Column('cancellation_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_rate_plan_id'], ['rate_plans.id'], name=op.f('fk_rate_plans_parent_rate_plan_id_rate_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_plans'))
    )
    op.create_index(op.f('ix_rate_plans_code'), 'rate_plans', ['code'], unique=True)
    op.create_table('auth_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], name=op.f('fk_auth_role_permissions_permission_id_auth_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], name=op.f('fk_auth_role_permissions_role_id_auth_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_auth_role_permissions'))
    )
    op.create_table('auth_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], name=op.f('fk_auth_user_roles_role_id_auth_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_auth_user_roles_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_auth_user_roles'))
    )
    op.create_table('avail_inventory_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sold_units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_avail_inventory_ledger_room_type_id_inv_room_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avail_inventory_ledger')),
    sa.UniqueConstraint('room_type_id', 'date', name='uq_ledger_room_type_date')
    )
    op.create_index(op.f('ix_avail_inventory_ledger_date'), 'avail_inventory_ledger', ['date'], unique=False)
    op.create_index(op.f('ix_avail_inventory_ledger_room_type_id'), 'avail_inventory_ledger', ['room_type_id'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('postcode', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('id_document_type', sa.String(length=30), nullable=False),
    sa.Column('id_document_number', sa.String(length=60), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['guest_companies.id'], name=op.f('fk_guests_company_id_guest_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_last_name'), 'guests', ['last_name'], unique=False)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=False)
    op.create_table('inv_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_inv_rooms_room_type_id_inv_room_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_rooms'))
    )
    op.create_index(op.f('ix_inv_rooms_number'), 'inv_rooms', ['number'], unique=True)
    op.create_index(op.f('ix_inv_rooms_room_type_id'), 'inv_rooms', ['room_type_id'], unique=False)
    op.create_table('rate_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], name=op.f('fk_rate_calendar_rate_plan_id_rate_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_rate_calendar_room_type_id_inv_room_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_calendar')),
    sa.UniqueConstraint('rate_plan_id', 'room_type_id', 'date', name='uq_rate_ppd')
    )
    op.create_index(op.f('ix_rate_calendar_date'), 'rate_calendar', ['date'], unique=False)
    op.create_index(op.f('ix_rate_calendar_rate_plan_id'), 'rate_calendar', ['rate_plan_id'], unique=False)
    op.create_index(op.f('ix_rate_calendar_room_type_id'), 'rate_calendar', ['room_type_id'], unique=False)
    op.create_table('rate_plan_room_types',
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], name=op.f('fk_rate_plan_room_types_rate_plan_id_rate_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_rate_plan_room_types_room_type_id_inv_room_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_plan_id', 'room_type_id', name=op.f('pk_rate_plan_room_types'))
    )
    op.create_table('rate_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_stay', sa.Integer(), nullable=False),
    sa.Column('max_stay', sa.Integer(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('closed_to_arrival', sa.Boolean(), nullable=False),
    sa.Column('closed_to_departure', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], name=op.f('fk_rate_restrictions_rate_plan_id_rate_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_rate_restrictions_room_type_id_inv_room_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_restrictions')),
    sa.UniqueConstraint('rate_plan_id', 'room_type_id', 'date', name='uq_restriction_ppd')
    )
    op.create_index(op.f('ix_rate_restrictions_date'), 'rate_restrictions', ['date'], unique=False)
    op.create_index(op.f('ix_rate_restrictions_rate_plan_id'), 'rate_restrictions', ['rate_plan_id'], unique=False)
    op.create_index(op.f('ix_rate_restrictions_room_type_id'), 'rate_restrictions', ['room_type_id'], unique=False)
    op.create_table('inv_room_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('out_of_order', 'maintenance', 'hold', 'other', name='blockreason', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['inv_rooms.id'], name=op.f('fk_inv_room_blocks_room_id_inv_rooms')),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_inv_room_blocks_room_type_id_inv_room_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_room_blocks')),
    sa.UniqueConstraint('room_id', 'start_date', name='uq_block_room_start')
    )
    op.create_index(op.f('ix_inv_room_blocks_end_date'), 'inv_room_blocks', ['end_date'], unique=False)
    op.create_index(op.f('ix_inv_room_blocks_room_id'), 'inv_room_blocks', ['room_id'], unique=False)
    op.create_index(op.f('ix_inv_room_blocks_room_type_id'), 'inv_room_blocks', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_inv_room_blocks_start_date'), 'inv_room_blocks', ['start_date'], unique=False)
    op.create_table('res_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('inquiry', 'confirmed', 'in_house', 'checked_out', 'cancelled', 'no_show', name='reservationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('source', sa.Enum('direct', 'phone', 'walk_in', 'ota', 'travel_agent', 'other', name='reservationsource', native_enum=False, length=40), nullable=False),
    sa.Column('channel_name', sa.String(length=60), nullable=False),
    sa.Column('external_reference', sa.String(length=80), nullable=False),
    sa.Column('primary_guest_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('arrival', sa.Date(), nullable=False),
    sa.Column('departure', sa.Date(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('cancellation_note', sa.Text(), nullable=False),
    sa.Column('free_cancel_until', sa.Date(), nullable=True),
    sa.Column('cancellation_penalty_nights', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['guest_companies.id'], name=op.f('fk_res_reservations_company_id_guest_companies')),
    sa.ForeignKeyConstraint(['primary_guest_id'], ['guests.id'], name=op.f('fk_res_reservations_primary_guest_id_guests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_res_reservations'))
    )
    op.create_index(op.f('ix_res_reservations_arrival'), 'res_reservations', ['arrival'], unique=False)
    op.create_index(op.f('ix_res_reservations_departure'), 'res_reservations', ['departure'], unique=False)
    op.create_index(op.f('ix_res_reservations_external_reference'), 'res_reservations', ['external_reference'], unique=False)
    op.create_index(op.f('ix_res_reservations_primary_guest_id'), 'res_reservations', ['primary_guest_id'], unique=False)
    op.create_index(op.f('ix_res_reservations_reference'), 'res_reservations', ['reference'], unique=True)
    op.create_index(op.f('ix_res_reservations_status'), 'res_reservations', ['status'], unique=False)
    op.create_table('bill_folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='foliostatus', native_enum=False, length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['res_reservations.id'], name=op.f('fk_bill_folios_reservation_id_res_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_folios'))
    )
    op.create_index(op.f('ix_bill_folios_code'), 'bill_folios', ['code'], unique=True)
    op.create_index(op.f('ix_bill_folios_reservation_id'), 'bill_folios', ['reservation_id'], unique=False)
    op.create_table('res_reservation_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('assigned_room_id', sa.Integer(), nullable=True),
    sa.Column('arrival', sa.Date(), nullable=False),
    sa.Column('departure', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('rate_total_minor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_room_id'], ['inv_rooms.id'], name=op.f('fk_res_reservation_rooms_assigned_room_id_inv_rooms')),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], name=op.f('fk_res_reservation_rooms_rate_plan_id_rate_plans')),
    sa.ForeignKeyConstraint(['reservation_id'], ['res_reservations.id'], name=op.f('fk_res_reservation_rooms_reservation_id_res_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['inv_room_types.id'], name=op.f('fk_res_reservation_rooms_room_type_id_inv_room_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_res_reservation_rooms'))
    )
    op.create_index(op.f('ix_res_reservation_rooms_arrival'), 'res_reservation_rooms', ['arrival'], unique=False)
    op.create_index(op.f('ix_res_reservation_rooms_assigned_room_id'), 'res_reservation_rooms', ['assigned_room_id'], unique=False)
    op.create_index(op.f('ix_res_reservation_rooms_departure'), 'res_reservation_rooms', ['departure'], unique=False)
    op.create_index(op.f('ix_res_reservation_rooms_reservation_id'), 'res_reservation_rooms', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_res_reservation_rooms_room_type_id'), 'res_reservation_rooms', ['room_type_id'], unique=False)
    op.create_table('bill_folio_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('charge', 'payment', 'tax', 'adjustment', name='foliolinekind', native_enum=False, length=40), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount_minor', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('parent_line_id', sa.Integer(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['folio_id'], ['bill_folios.id'], name=op.f('fk_bill_folio_lines_folio_id_bill_folios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_line_id'], ['bill_folio_lines.id'], name=op.f('fk_bill_folio_lines_parent_line_id_bill_folio_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_folio_lines'))
    )
    op.create_index(op.f('ix_bill_folio_lines_folio_id'), 'bill_folio_lines', ['folio_id'], unique=False)
    op.create_table('bill_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bill_to_name', sa.String(length=200), nullable=False),
    sa.Column('bill_to_address', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('lines_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folio_id'], ['bill_folios.id'], name=op.f('fk_bill_invoices_folio_id_bill_folios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_invoices'))
    )
    op.create_index(op.f('ix_bill_invoices_folio_id'), 'bill_invoices', ['folio_id'], unique=False)
    op.create_index(op.f('ix_bill_invoices_number'), 'bill_invoices', ['number'], unique=True)
    op.create_table('fd_room_assignment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_room_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('previous_room_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('assigned', 'moved', 'released', name='assignmentaction', native_enum=False, length=40), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['previous_room_id'], ['inv_rooms.id'], name=op.f('fk_fd_room_assignment_log_previous_room_id_inv_rooms')),
    sa.ForeignKeyConstraint(['reservation_room_id'], ['res_reservation_rooms.id'], name=op.f('fk_fd_room_assignment_log_reservation_room_id_res_reservation_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['inv_rooms.id'], name=op.f('fk_fd_room_assignment_log_room_id_inv_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fd_room_assignment_log'))
    )
    op.create_index(op.f('ix_fd_room_assignment_log_reservation_room_id'), 'fd_room_assignment_log', ['reservation_room_id'], unique=False)
    op.create_table('res_reservation_room_nights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('posted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_room_id'], ['res_reservation_rooms.id'], name=op.f('fk_res_reservation_room_nights_reservation_room_id_res_reservation_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_res_reservation_room_nights'))
    )
    op.create_index(op.f('ix_res_reservation_room_nights_date'), 'res_reservation_room_nights', ['date'], unique=False)
    op.create_index(op.f('ix_res_reservation_room_nights_reservation_room_id'), 'res_reservation_room_nights', ['reservation_room_id'], unique=False)
    op.create_table('bill_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_line_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['folio_line_id'], ['bill_folio_lines.id'], name=op.f('fk_bill_payments_folio_line_id_bill_folio_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_payments')),
    sa.UniqueConstraint('folio_line_id', name=op.f('uq_bill_payments_folio_line_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_payments')
    op.drop_index(op.f('ix_res_reservation_room_nights_reservation_room_id'), table_name='res_reservation_room_nights')
    op.drop_index(op.f('ix_res_reservation_room_nights_date'), table_name='res_reservation_room_nights')
    op.drop_table('res_reservation_room_nights')
    op.drop_index(op.f('ix_fd_room_assignment_log_reservation_room_id'), table_name='fd_room_assignment_log')
    op.drop_table('fd_room_assignment_log')
    op.drop_index(op.f('ix_bill_invoices_number'), table_name='bill_invoices')
    op.drop_index(op.f('ix_bill_invoices_folio_id'), table_name='bill_invoices')
    op.drop_table('bill_invoices')
    op.drop_index(op.f('ix_bill_folio_lines_folio_id'), table_name='bill_folio_lines')
    op.drop_table('bill_folio_lines')
    op.drop_index(op.f('ix_res_reservation_rooms_room_type_id'), table_name='res_reservation_rooms')
    op.drop_index(op.f('ix_res_reservation_rooms_reservation_id'), table_name='res_reservation_rooms')
    op.drop_index(op.f('ix_res_reservation_rooms_departure'), table_name='res_reservation_rooms')
    op.drop_index(op.f('ix_res_reservation_rooms_assigned_room_id'), table_name='res_reservation_rooms')
    op.drop_index(op.f('ix_res_reservation_rooms_arrival'), table_name='res_reservation_rooms')
    op.drop_table('res_reservation_rooms')
    op.drop_index(op.f('ix_bill_folios_reservation_id'), table_name='bill_folios')
    op.drop_index(op.f('ix_bill_folios_code'), table_name='bill_folios')
    op.drop_table('bill_folios')
    op.drop_index(op.f('ix_res_reservations_status'), table_name='res_reservations')
    op.drop_index(op.f('ix_res_reservations_reference'), table_name='res_reservations')
    op.drop_index(op.f('ix_res_reservations_primary_guest_id'), table_name='res_reservations')
    op.drop_index(op.f('ix_res_reservations_external_reference'), table_name='res_reservations')
    op.drop_index(op.f('ix_res_reservations_departure'), table_name='res_reservations')
    op.drop_index(op.f('ix_res_reservations_arrival'), table_name='res_reservations')
    op.drop_table('res_reservations')
    op.drop_index(op.f('ix_inv_room_blocks_start_date'), table_name='inv_room_blocks')
    op.drop_index(op.f('ix_inv_room_blocks_room_type_id'), table_name='inv_room_blocks')
    op.drop_index(op.f('ix_inv_room_blocks_room_id'), table_name='inv_room_blocks')
    op.drop_index(op.f('ix_inv_room_blocks_end_date'), table_name='inv_room_blocks')
    op.drop_table('inv_room_blocks')
    op.drop_index(op.f('ix_rate_restrictions_room_type_id'), table_name='rate_restrictions')
    op.drop_index(op.f('ix_rate_restrictions_rate_plan_id'), table_name='rate_restrictions')
    op.drop_index(op.f('ix_rate_restrictions_date'), table_name='rate_restrictions')
    op.drop_table('rate_restrictions')
    op.drop_table('rate_plan_room_types')
    op.drop_index(op.f('ix_rate_calendar_room_type_id'), table_name='rate_calendar')
    op.drop_index(op.f('ix_rate_calendar_rate_plan_id'), table_name='rate_calendar')
    op.drop_index(op.f('ix_rate_calendar_date'), table_name='rate_calendar')
    op.drop_table('rate_calendar')
    op.drop_index(op.f('ix_inv_rooms_room_type_id'), table_name='inv_rooms')
    op.drop_index(op.f('ix_inv_rooms_number'), table_name='inv_rooms')
    op.drop_table('inv_rooms')
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_last_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_avail_inventory_ledger_room_type_id'), table_name='avail_inventory_ledger')
    op.drop_index(op.f('ix_avail_inventory_ledger_date'), table_name='avail_inventory_ledger')
    op.drop_table('avail_inventory_ledger')
    op.drop_table('auth_user_roles')
    op.drop_table('auth_role_permissions')
    op.drop_index(op.f('ix_rate_plans_code'), table_name='rate_plans')
    op.drop_table('rate_plans')
    op.drop_index(op.f('ix_inv_room_types_code'), table_name='inv_room_types')
    op.drop_table('inv_room_types')
    op.drop_table('inv_property')
    op.drop_index(op.f('ix_guest_companies_name'), table_name='guest_companies')
    op.drop_table('guest_companies')
    op.drop_table('bill_tax_rules')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_roles_code'), table_name='auth_roles')
    op.drop_table('auth_roles')
    op.drop_index(op.f('ix_auth_permissions_code'), table_name='auth_permissions')
    op.drop_table('auth_permissions')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
