"""tax_inclusive rules + folio line tax component

Revision ID: 87b9a0e244d2
Revises: 33755596570f
Create Date: 2026-08-30 20:38:45.287594
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '87b9a0e244d2'
down_revision: str | None = '33755596570f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bill_folio_lines',
        sa.Column('tax_component_minor', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'bill_tax_rules',
        sa.Column('tax_inclusive', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('bill_folio_lines', 'tax_component_minor', server_default=None)
    op.alter_column('bill_tax_rules', 'tax_inclusive', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_tax_rules', 'tax_inclusive')
    op.drop_column('bill_folio_lines', 'tax_component_minor')
    # ### end Alembic commands ###
